version: 2.1
orbs:
  node: circleci/node@5.2.0
  codecov: codecov/codecov@4.1.0

jobs:
  tests:
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run:
          name: Debug codecov
          command: ./node_modules/.bin/codecov -t $CODECOV_TOKEN
          
      - codecov/upload:
          file: ../coverage/*.json
workflows:
  ci:
    jobs:
      - tests
