version: 2.1
orbs:
  node: circleci/node@5.2.0
  codecov: codecov/codecov@4.1.0

jobs:
  tests:
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - codecov/upload:
          file: coverage/*.json
          token: b3b00bbf-67f2-4284-8edf-8eb1050a1d13

workflows:
  ci:
    jobs:
      - tests
