version: 2.1
orbs:
  node: circleci/node@5.2.0
  codecov: codecov/codecov@4.1.0

jobs:
  tests:
    docker:
      - image: cimg/node:21.7.3
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
      - run:
          name: Install codecov
          command: | curl -s https://codecov.io/bash > codecov chmod +x codecov
          
      - run:
          name: Debug codecov
          command: ./codecov -t $CODECOV_TOKEN -d
      - codecov/upload:
          file: coverage/*.json

workflows:
  ci:
    jobs:
      - tests
