version: 2.1
orbs:
  node: circleci/node@5.2.0

jobs:
  setup:
    docker:
      - image: circleci/node:20.12.2-browsers
    steps:
      - checkout
      - node/install
          install-yarn: false
      - run: node --version
      - run: yarn --version
workflows:
  ci:
    jobs:
      - setup

  
